apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: deployment-poc-angular
spec:
  replicas: 1
  template:
    metadata:
      labels:
        label-key : label-value  
    spec:
      containers:
        - name: deploment-container-name
          image: inyee/spa-demo:v1
          imagePullPolicy: Always
          ports:
          - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: service-poc-angular
  name: service-name-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - name: service-port-name
    port: 80
    protocol: TCP
  selector:
    deployment-label-key: deployment-label-value